project:
  type: book
  output-dir: docs

book:
  title: "Regional Analysis"
  author: "Luke Heley"
  date: "28/01/2024"
  chapters:
    - index.qmd
    - lossiemouth.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo