project:
  type: book

book:
  title: "Regional Analysis"
  author: "Luke Heley"
  date: "28/01/2024"
  chapters:
    - index.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  epub:
    cover-image: cover.png